### PR TITLE
Move from vue-ajax to axios

### PR DESCRIPTION
**Pull request by Serubin**
## Summary
Switch ajax library from vue-h-ajax to axios.

## Motivation
The motivation for this encompasses two things - 
1) Testability - testing with the Vue context is annoying and not necessary
2) Maintainability - vue-ajax has very little support

## Test Plan
Click testing... for now.

### CODE REVIEW

**Comment by klinker24** [comment]
🙌 I love axios, it works great. I will take a look at this and test it out, tomorrow 👍

**Comment by Serubin** [comment]
The API doesn't return any other status codes than 200 correct?

**Comment by Serubin** [comment]
^ doesn't matter.

Resolved the issue

**Comment by klinker24** [comment]
The only other status code that the API returns is 401 unauthorized. Unless there is some sort of exception that happens, obviously. Looks good to me, thanks!

**Pull request merged**
